# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 15:52
from __future__ import unicode_literals

from django.contrib.auth.models import User, Permission
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


def add_admin_user(apps, schema_editor):
    admin_user_data = {'username': 'admin', 'email': 'admin@dynforms.pl',
                       'password': 'admin', 'is_superuser': True,
                       'first_name': 'Admin', 'last_name': 'Admin'}
    User.objects.create_user(**admin_user_data).save()


def add_permission_to_translate(apps, schema_editor):
    unused_content_type = ContentType.objects.create(app_label='dynforms',
                                                     model='unused')
    can_translate_permission = Permission.objects.create(name='Can translate forms',
                                                         content_type=unused_content_type,
                                                         codename='can_translate_forms')
    can_translate_permission.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(add_admin_user),
        migrations.RunPython(add_permission_to_translate)
    ]
