# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 11:37
from __future__ import unicode_literals

from django.db import migrations, models

from dynforms.models import Language


def add_default_languages(apps, schema_editor):
    Language.objects.create(code='en', name='English').save()
    Language.objects.create(code='pl', name='Polski').save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dynforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RunPython(add_default_languages)
    ]
