# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynforms', '0002_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('max_submissions', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
