# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynforms', '0003_formmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmodel',
            name='languages',
            field=models.ManyToManyField(related_name='_formmodel_languages_+', to='dynforms.Language'),
        ),
    ]
