# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-24 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynforms', '0004_formmodel_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(max_length=20)),
                ('field_label', models.CharField(max_length=100)),
                ('field_placeholder', models.CharField(max_length=500, null=True)),
                ('field_required', models.BooleanField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynforms.FormModel')),
            ],
        ),
    ]
