# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 18:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynforms', '0005_formfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynforms.FormModel')),
            ],
        ),
        migrations.CreateModel(
            name='TextTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('translated', models.CharField(max_length=1000, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynforms.Language')),
            ],
        ),
        migrations.AlterModelOptions(
            name='formfield',
            options={'ordering': ['id']},
        ),
    ]
